# This is a basic workflow to help you get started with Actions

name: CI

permissions:
  contents: write
  pages: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Doxygen
        uses: mattnotmitt/doxygen-action@v1.2.1
        with:
          doxyfile-path: ./doxyfile
          working-directory: .
      - name: VIPRA Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
  
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install -y mpich libmpich-dev
      - name: Run CMake
        run: cd __tests__ && cmake -B build -S .
      - name: Build
        run: cd __tests__ && cmake --build build
      - name: Run tests
        run: cd __tests__ && build/vipra_tests
